hpc <- read.delim("household_power_consumption.txt", header = TRUE, sep = ";")
hpc$Date <- dmy(hpc$Date)
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc <- subset(hpc, Date == "2007-02-01" | Date == "2007-02-02")
png("plot1.png")
hist(hpc$Global_active_power,col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()